//
// The orange post from dod_alpine, converted into static prop for assorted reasons
// subdivided a resonable amount in order to retain lighting comparable to the lightmap
//

$modelname "dod_alpine/orange_post/0_vertexlit.mdl"
$cdmaterials "models/dev"

$staticprop
$surfaceprop concrete

$body studio "orange_post"

$collisionmodel "orange_post_terrain" { $concave }

$sequence "idle" "orange_post"
